apiVersion: apps/v1
kind: Deployment
metadata:
  name: spp-docs
  labels:
    app: spp-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spp-docs
  template:
    metadata:
      labels:
        app: spp-docs
    spec:
      containers:
        - name: spp-docs
          image: "ghcr.io/sourceplusplus/documentation:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: spp-cloud-registry
---
apiVersion: v1
kind: Service
metadata:
  name: spp-docs
spec:
  selector:
    app: spp-docs
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
