name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'docs'

      - name: Setup MkDocs
        run: |
          sudo apt update
          sudo apt install python3-pip
          sudo apt-get install mkdocs
          pip3 install mkdocs-material
          pip3 install mkdocs-awesome-pages-plugin
          pip3 install fancyboxmd
          pip3 install mkdocs-macros-plugin
          pip3 install mkdocs-git-revision-date-localized-plugin

      - name: Build docs
        run: mkdocs build && mv site html

      - name: Update docs.sourceplus.plus
        if: github.ref == 'refs/heads/master'
        uses: appleboy/scp-action@master
        with:
          host: docs.sourceplus.plus
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "html/*"
          target: "/var/www/"
          overwrite: true
